spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/slt
    username: sltuser
    password: sltpass
    driver-class-name: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

