spring:
  config:
    import: "optional:classpath:application-api.yml"

  datasource:
    url: jdbc:postgresql://localhost:5432/slt
    username: sltuser
    password: sltpass
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

    # 이메일 설정 (Gmail SMTP 예시)
    # application-api.yml에 정의된 MMB 값들을 매핑
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
       mail:
         smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID:}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET:}
            scope: [ email, profile ]
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

          kakao:
            client-id: ${OAUTH_KAKAO_CLIENT_ID:}
            client-secret: ${OAUTH_KAKAO_CLIENT_SECRET:}
            scope: [ account_email, profile_nickname ]
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-name: Kakao
            client-authentication-method: client_secret_post

          naver:
            client-id: ${OAUTH_NAVER_CLIENT_ID:}
            client-secret: ${OAUTH_NAVER_CLIENT_SECRET:}
            scope: [ name, email ]
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/naver"

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  address: 0.0.0.0
  port: 8082

mybatis:
  configuration:
    map-underscore-to-camel-case: true

kcisa:
  base-url: https://api.kcisa.kr/openapi/service/rest/meta13/getCTE01701
  service-key: 1099ca75-c757-450f-bb0f-3f7f4d90833f
  num-of-rows: 10

jwt:
  secret: ${JWT_SECRET:dev-secret-please-change-this-32chars-min}
  access-token:
    exp-minutes: ${ACCESS_TOKEN_EXP_MINUTES:60}
  refresh-token:
    exp-days: ${REFRESH_TOKEN_EXP_DAYS:7}

app:
  frontend-redirect-uri: ${FRONTEND_REDIRECT_URI:http://localhost:5173/oauth2/success}
  openai:
    api-key: ${OPENAI_API_KEY}
  help:
    vector-cache-path: D:/temp/help-vectors.json